# Form implementation generated from reading ui file 'C:\Users\admin\PycharmProjects\K22416C\Sales_management\UI\login_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\admin\\PycharmProjects\\K22416C\\Sales_management\\UI\\../Images/605508_bag_buy_cart_item_sale_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 71, 21))
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username.setGeometry(QtCore.QRect(170, 80, 211, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(170, 140, 211, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 110, 51, 21))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(170, 180, 181, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_Dangnhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Dangnhap.setGeometry(QtCore.QRect(170, 210, 91, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\admin\\PycharmProjects\\K22416C\\Sales_management\\UI\\../Images/login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Dangnhap.setIcon(icon1)
        self.pushButton_Dangnhap.setObjectName("pushButton_Dangnhap")
        self.pushButton_Thoat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Thoat.setGeometry(QtCore.QRect(290, 210, 91, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\admin\\PycharmProjects\\K22416C\\Sales_management\\UI\\../Images/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Thoat.setIcon(icon2)
        self.pushButton_Thoat.setObjectName("pushButton_Thoat")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 131, 151))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\admin\\PycharmProjects\\K22416C\\Sales_management\\UI\\../Images/131507_hacker_administrator_system_sys_hack_icon (1).png"))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 454, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_Thoat.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hệ thống máy học ABC"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP HỆ THỐNG"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Lưu thông tin đăng nhập "))
        self.pushButton_Dangnhap.setText(_translate("MainWindow", "Đăng nhập"))
        self.pushButton_Thoat.setText(_translate("MainWindow", "Thoát"))
